version: "3"
services:
  app: # includes php and nginx
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: teleprompt/app
    ports:
      - ${DOCKER_APP_PORT}:80
    environment:
      WWWUSER: ${DOCKER_WWWUSER}
      GIT_USER_NAME: ${DOCKER_GIT_USER_NAME}
      GIT_USER_EMAIL: ${DOCKER_GIT_USER_EMAIL}
    networks:
      - app_network
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
  redis:
    image: redis:alpine
    networks:
      - app_network
    volumes:
      - data_redis:/data
  mysql:
    image: mysql:5.7
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - app_network
    volumes:
      - data_mysql:/var/lib/mysql
networks:
  app_network:
    driver: bridge
volumes:
  data_mysql:
    driver: local
  data_redis:
    driver: local
